# 每天 23:59:00 执行
# UTC 时间，北京时间需要 UTC+8
name: Start

on:
   workflow_dispatch:
   schedule:
       - cron: '39 15 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      env:
        COOKIE: ${{ secrets.COOKIE }}
      run: |
        mvn compile exec:java -Dexec.mainClass="org.example.Main" -Dexec.args="${COOKIE}"
